import {
  WATER_SPOT_CATEGORIES,
  type WaterSpotCategory,
} from "@/lib/geo/water-spot-category";

/** 类型与本地兜底数据（API 不可用时使用） */
export type FishingSpot = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  /** 水域：水库、湖泊、江河、黑坑（与钓点 Tab、作钓记录、后台一致） */
  waterCategory?: WaterSpotCategory;
  fish?: string;
  /** 地区关键词，用于搜索 */
  region?: string;
  distanceLabel?: string;
  rating?: number;
};

export type MapCenter = { lat: number; lng: number };

export const DEFAULT_MAP_CENTER: MapCenter = { lat: 30.544, lng: 114.429 };

/** 人工精选钓点：作为全国钓点库的高质量头部数据 */
const CURATED_FISHING_SPOTS: FishingSpot[] = [
  {
    id: "1",
    name: "东湖钓点",
    lat: 30.5521,
    lng: 114.4382,
    waterCategory: "湖泊",
    fish: "草鱼、鲤鱼",
    region: "武汉 东湖",
    distanceLabel: "2.3km",
    rating: 4.5,
  },
  {
    id: "2",
    name: "西山水库",
    lat: 30.4984,
    lng: 114.3821,
    waterCategory: "水库",
    fish: "鲈鱼、黑鱼",
    region: "武汉 西山",
    distanceLabel: "5.6km",
    rating: 4.8,
  },
  {
    id: "3",
    name: "渔乐钓场",
    lat: 30.5198,
    lng: 114.4095,
    waterCategory: "黑坑",
    region: "武汉",
    distanceLabel: "12.1km",
    rating: undefined,
  },
  {
    id: "4",
    name: "青龙湖",
    lat: 30.5602,
    lng: 114.3598,
    waterCategory: "湖泊",
    region: "武汉 江夏",
    distanceLabel: "16.7km",
    rating: 4.13,
  },
  {
    id: "5",
    name: "汤逊湖渔湾",
    lat: 30.4386,
    lng: 114.3728,
    waterCategory: "湖泊",
    fish: "鲫鱼、鳊鱼、翘嘴",
    region: "武汉 江夏 汤逊湖",
    distanceLabel: "18.4km",
    rating: 4.6,
  },
  {
    id: "6",
    name: "梁子湖龙湾钓点",
    lat: 30.2569,
    lng: 114.5985,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "鄂州 梁子湖",
    distanceLabel: "42.8km",
    rating: 4.7,
  },
  {
    id: "7",
    name: "府河湿地钓点",
    lat: 30.6892,
    lng: 114.2317,
    waterCategory: "江河",
    fish: "鲫鱼、鲤鱼、黄颡鱼",
    region: "武汉 东西湖 府河",
    distanceLabel: "23.5km",
    rating: 4.2,
  },
  {
    id: "8",
    name: "汉江月湖桥钓点",
    lat: 30.5665,
    lng: 114.2472,
    waterCategory: "江河",
    fish: "鳊鱼、翘嘴、鲢鳙",
    region: "武汉 汉阳 汉江",
    distanceLabel: "14.9km",
    rating: 4.4,
  },
  {
    id: "9",
    name: "严西湖浅滩",
    lat: 30.5306,
    lng: 114.5247,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "武汉 洪山 严西湖",
    distanceLabel: "19.6km",
    rating: 4.35,
  },
  {
    id: "10",
    name: "金银湖亲水钓点",
    lat: 30.6423,
    lng: 114.2086,
    waterCategory: "湖泊",
    fish: "鲫鱼、白条、鳊鱼",
    region: "武汉 东西湖 金银湖",
    distanceLabel: "21.2km",
    rating: 4.1,
  },
  {
    id: "11",
    name: "后官湖绿道钓点",
    lat: 30.5214,
    lng: 114.1027,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、黑鱼",
    region: "武汉 蔡甸 后官湖",
    distanceLabel: "31.8km",
    rating: 4.3,
  },
  {
    id: "12",
    name: "涨渡湖野钓点",
    lat: 30.6418,
    lng: 114.7236,
    waterCategory: "湖泊",
    fish: "鲫鱼、鳊鱼、翘嘴",
    region: "武汉 新洲 涨渡湖",
    distanceLabel: "54.5km",
    rating: 4.55,
  },
  {
    id: "13",
    name: "鲁湖水库",
    lat: 30.3172,
    lng: 114.4331,
    waterCategory: "水库",
    fish: "青鱼、草鱼、鲢鳙",
    region: "武汉 江夏 鲁湖",
    distanceLabel: "36.4km",
    rating: 4.65,
  },
  {
    id: "14",
    name: "木兰湖水库湾",
    lat: 31.0709,
    lng: 114.3675,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、鳜鱼",
    region: "武汉 黄陂 木兰湖",
    distanceLabel: "61.3km",
    rating: 4.5,
  },
  {
    id: "15",
    name: "长江青山矶钓点",
    lat: 30.6393,
    lng: 114.4225,
    waterCategory: "江河",
    fish: "鳊鱼、鲶鱼、翘嘴",
    region: "武汉 青山 长江",
    distanceLabel: "18.7km",
    rating: 4.25,
  },
  {
    id: "16",
    name: "星悦竞技钓场",
    lat: 30.4738,
    lng: 114.2896,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "武汉 江夏 黑坑",
    distanceLabel: "24.6km",
    rating: 4.9,
  },
  {
    id: "17",
    name: "光谷休闲钓场",
    lat: 30.4741,
    lng: 114.4808,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "武汉 东湖高新 光谷",
    distanceLabel: "17.8km",
    rating: 4.4,
  },
  {
    id: "18",
    name: "藏龙岛湿地钓点",
    lat: 30.4315,
    lng: 114.4176,
    waterCategory: "湖泊",
    fish: "鲫鱼、黑鱼、黄颡鱼",
    region: "武汉 江夏 藏龙岛",
    distanceLabel: "22.3km",
    rating: 4.2,
  },
  {
    id: "19",
    name: "密云水库观景湾",
    lat: 40.5174,
    lng: 116.9465,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、翘嘴",
    region: "北京 密云",
    distanceLabel: "全国钓点",
    rating: 4.6,
  },
  {
    id: "20",
    name: "十三陵水库休闲钓点",
    lat: 40.2568,
    lng: 116.2369,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "北京 昌平",
    distanceLabel: "全国钓点",
    rating: 4.3,
  },
  {
    id: "21",
    name: "于桥水库岸钓区",
    lat: 40.0456,
    lng: 117.4652,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、白条",
    region: "天津 蓟州",
    distanceLabel: "全国钓点",
    rating: 4.25,
  },
  {
    id: "22",
    name: "千岛湖中心湖区钓点",
    lat: 29.6088,
    lng: 119.0436,
    waterCategory: "湖泊",
    fish: "翘嘴、鳜鱼、鲢鳙",
    region: "浙江 杭州 淳安",
    distanceLabel: "全国钓点",
    rating: 4.85,
  },
  {
    id: "23",
    name: "太湖西山岛钓点",
    lat: 31.1094,
    lng: 120.2738,
    waterCategory: "湖泊",
    fish: "鲫鱼、鳊鱼、翘嘴",
    region: "江苏 苏州 太湖",
    distanceLabel: "全国钓点",
    rating: 4.55,
  },
  {
    id: "24",
    name: "巢湖滨湖钓点",
    lat: 31.6017,
    lng: 117.5258,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、黄颡鱼",
    region: "安徽 合肥 巢湖",
    distanceLabel: "全国钓点",
    rating: 4.35,
  },
  {
    id: "25",
    name: "鄱阳湖都昌钓点",
    lat: 29.2865,
    lng: 116.2043,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "江西 九江 鄱阳湖",
    distanceLabel: "全国钓点",
    rating: 4.7,
  },
  {
    id: "26",
    name: "洞庭湖岳阳钓点",
    lat: 29.3491,
    lng: 113.1194,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "湖南 岳阳 洞庭湖",
    distanceLabel: "全国钓点",
    rating: 4.65,
  },
  {
    id: "27",
    name: "滇池海埂钓点",
    lat: 24.9657,
    lng: 102.6548,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、白条",
    region: "云南 昆明 滇池",
    distanceLabel: "全国钓点",
    rating: 4.15,
  },
  {
    id: "28",
    name: "洱海双廊钓点",
    lat: 25.8976,
    lng: 100.1912,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、翘嘴",
    region: "云南 大理 洱海",
    distanceLabel: "全国钓点",
    rating: 4.55,
  },
  {
    id: "29",
    name: "青海湖黑马河钓点",
    lat: 36.7658,
    lng: 99.7885,
    waterCategory: "湖泊",
    fish: "高原冷水鱼",
    region: "青海 海南州 青海湖",
    distanceLabel: "全国钓点",
    rating: 4.3,
  },
  {
    id: "30",
    name: "衡水湖芦苇湾",
    lat: 37.6288,
    lng: 115.7056,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、黑鱼",
    region: "河北 衡水 衡水湖",
    distanceLabel: "全国钓点",
    rating: 4.4,
  },
  {
    id: "31",
    name: "查干湖冬捕水域",
    lat: 45.2327,
    lng: 124.3269,
    waterCategory: "湖泊",
    fish: "鲤鱼、鲫鱼、鳙鱼",
    region: "吉林 松原 查干湖",
    distanceLabel: "全国钓点",
    rating: 4.7,
  },
  {
    id: "32",
    name: "镜泊湖吊水楼湾",
    lat: 43.8919,
    lng: 128.9862,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、哲罗鱼",
    region: "黑龙江 牡丹江 镜泊湖",
    distanceLabel: "全国钓点",
    rating: 4.6,
  },
  {
    id: "33",
    name: "丹江口水库大坝湾",
    lat: 32.5401,
    lng: 111.5086,
    waterCategory: "水库",
    fish: "翘嘴、鳜鱼、鲢鳙",
    region: "湖北 十堰 丹江口",
    distanceLabel: "全国钓点",
    rating: 4.8,
  },
  {
    id: "34",
    name: "三峡库区秭归钓点",
    lat: 30.8252,
    lng: 110.9765,
    waterCategory: "水库",
    fish: "鲤鱼、草鱼、鲶鱼",
    region: "湖北 宜昌 三峡库区",
    distanceLabel: "全国钓点",
    rating: 4.75,
  },
  {
    id: "35",
    name: "升钟湖钓点",
    lat: 31.5449,
    lng: 105.8842,
    waterCategory: "水库",
    fish: "翘嘴、鲫鱼、鲤鱼",
    region: "四川 南充 升钟湖",
    distanceLabel: "全国钓点",
    rating: 4.82,
  },
  {
    id: "36",
    name: "鲁班水库钓点",
    lat: 31.0616,
    lng: 105.0453,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "四川 绵阳 鲁班水库",
    distanceLabel: "全国钓点",
    rating: 4.5,
  },
  {
    id: "37",
    name: "红枫湖钓点",
    lat: 26.5078,
    lng: 106.4163,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "贵州 贵阳 清镇",
    distanceLabel: "全国钓点",
    rating: 4.45,
  },
  {
    id: "38",
    name: "万峰湖罗甸湾",
    lat: 25.0914,
    lng: 105.1536,
    waterCategory: "水库",
    fish: "罗非、翘嘴、鲤鱼",
    region: "贵州 黔西南 万峰湖",
    distanceLabel: "全国钓点",
    rating: 4.85,
  },
  {
    id: "39",
    name: "龙羊峡水库钓点",
    lat: 36.1236,
    lng: 100.9061,
    waterCategory: "水库",
    fish: "虹鳟、鲤鱼、冷水鱼",
    region: "青海 海南州 龙羊峡",
    distanceLabel: "全国钓点",
    rating: 4.55,
  },
  {
    id: "40",
    name: "新安江水库深水湾",
    lat: 29.4982,
    lng: 118.9612,
    waterCategory: "水库",
    fish: "翘嘴、鳜鱼、鲢鳙",
    region: "浙江 杭州 新安江",
    distanceLabel: "全国钓点",
    rating: 4.72,
  },
  {
    id: "41",
    name: "响洪甸水库钓点",
    lat: 31.4768,
    lng: 116.2279,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "安徽 六安 金寨",
    distanceLabel: "全国钓点",
    rating: 4.42,
  },
  {
    id: "42",
    name: "鸭河口水库钓点",
    lat: 33.1514,
    lng: 112.6847,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "河南 南阳 鸭河口",
    distanceLabel: "全国钓点",
    rating: 4.35,
  },
  {
    id: "43",
    name: "南湾水库钓点",
    lat: 32.0833,
    lng: 114.0187,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "河南 信阳 南湾湖",
    distanceLabel: "全国钓点",
    rating: 4.5,
  },
  {
    id: "44",
    name: "官厅水库妫水湾",
    lat: 40.3646,
    lng: 115.7142,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "河北 张家口 官厅水库",
    distanceLabel: "全国钓点",
    rating: 4.38,
  },
  {
    id: "45",
    name: "黄河郑州花园口",
    lat: 34.9167,
    lng: 113.6826,
    waterCategory: "江河",
    fish: "鲤鱼、鲶鱼、黄颡鱼",
    region: "河南 郑州 黄河",
    distanceLabel: "全国钓点",
    rating: 4.3,
  },
  {
    id: "46",
    name: "长江南京江心洲钓点",
    lat: 32.0303,
    lng: 118.7319,
    waterCategory: "江河",
    fish: "鳊鱼、鲶鱼、翘嘴",
    region: "江苏 南京 长江",
    distanceLabel: "全国钓点",
    rating: 4.28,
  },
  {
    id: "47",
    name: "珠江番禺水道钓点",
    lat: 22.9281,
    lng: 113.3673,
    waterCategory: "江河",
    fish: "罗非、鲮鱼、鲤鱼",
    region: "广东 广州 珠江",
    distanceLabel: "全国钓点",
    rating: 4.32,
  },
  {
    id: "48",
    name: "东江惠州潼湖钓点",
    lat: 23.0589,
    lng: 114.3774,
    waterCategory: "江河",
    fish: "鲮鱼、罗非、翘嘴",
    region: "广东 惠州 东江",
    distanceLabel: "全国钓点",
    rating: 4.58,
  },
  {
    id: "49",
    name: "松花江哈尔滨江段",
    lat: 45.7938,
    lng: 126.5862,
    waterCategory: "江河",
    fish: "鲫鱼、鲤鱼、鲶鱼",
    region: "黑龙江 哈尔滨 松花江",
    distanceLabel: "全国钓点",
    rating: 4.36,
  },
  {
    id: "50",
    name: "漓江阳朔钓点",
    lat: 24.7786,
    lng: 110.4969,
    waterCategory: "江河",
    fish: "鲫鱼、鲤鱼、马口",
    region: "广西 桂林 阳朔 漓江",
    distanceLabel: "全国钓点",
    rating: 4.5,
  },
  {
    id: "51",
    name: "青浦淀山湖钓点",
    lat: 31.1102,
    lng: 120.9567,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "上海 青浦 淀山湖",
    distanceLabel: "全国钓点",
    rating: 4.4,
  },
  {
    id: "52",
    name: "滴水湖东岸钓点",
    lat: 30.9045,
    lng: 121.9321,
    waterCategory: "湖泊",
    fish: "鲈鱼、鲻鱼、鲫鱼",
    region: "上海 浦东 临港",
    distanceLabel: "全国钓点",
    rating: 4.18,
  },
  {
    id: "53",
    name: "深圳铁岗水库外围钓点",
    lat: 22.6236,
    lng: 113.9062,
    waterCategory: "水库",
    fish: "罗非、鲫鱼、鲤鱼",
    region: "广东 深圳 宝安",
    distanceLabel: "全国钓点",
    rating: 4.12,
  },
  {
    id: "54",
    name: "厦门杏林湾钓点",
    lat: 24.5743,
    lng: 118.0432,
    waterCategory: "湖泊",
    fish: "鲻鱼、鲈鱼、罗非",
    region: "福建 厦门 集美",
    distanceLabel: "全国钓点",
    rating: 4.26,
  },
  {
    id: "55",
    name: "福州闽江南港钓点",
    lat: 26.0429,
    lng: 119.3068,
    waterCategory: "江河",
    fish: "鲤鱼、鲫鱼、鲈鱼",
    region: "福建 福州 闽江",
    distanceLabel: "全国钓点",
    rating: 4.31,
  },
  {
    id: "56",
    name: "西安浐河城市钓点",
    lat: 34.2985,
    lng: 109.0338,
    waterCategory: "江河",
    fish: "鲫鱼、鲤鱼、白条",
    region: "陕西 西安 浐河",
    distanceLabel: "全国钓点",
    rating: 4.2,
  },
  {
    id: "57",
    name: "昆明松华坝水库钓点",
    lat: 25.1346,
    lng: 102.7946,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、白条",
    region: "云南 昆明 松华坝",
    distanceLabel: "全国钓点",
    rating: 4.22,
  },
  {
    id: "58",
    name: "重庆长寿湖钓点",
    lat: 29.9421,
    lng: 107.2519,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、翘嘴",
    region: "重庆 长寿 长寿湖",
    distanceLabel: "全国钓点",
    rating: 4.68,
  },
  {
    id: "59",
    name: "成都三岔湖钓点",
    lat: 30.2727,
    lng: 104.2849,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、翘嘴",
    region: "四川 成都 简阳",
    distanceLabel: "全国钓点",
    rating: 4.62,
  },
  {
    id: "60",
    name: "成都黑龙滩钓点",
    lat: 30.0528,
    lng: 103.9397,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "四川 眉山 仁寿",
    distanceLabel: "全国钓点",
    rating: 4.58,
  },
  {
    id: "61",
    name: "长沙松雅湖钓点",
    lat: 28.2548,
    lng: 113.1014,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、鳊鱼",
    region: "湖南 长沙 松雅湖",
    distanceLabel: "全国钓点",
    rating: 4.3,
  },
  {
    id: "62",
    name: "南昌艾溪湖钓点",
    lat: 28.6855,
    lng: 115.9959,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、白条",
    region: "江西 南昌 艾溪湖",
    distanceLabel: "全国钓点",
    rating: 4.18,
  },
  {
    id: "63",
    name: "济南大明湖休闲钓点",
    lat: 36.6742,
    lng: 117.0259,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、白条",
    region: "山东 济南 大明湖",
    distanceLabel: "全国钓点",
    rating: 4.08,
  },
  {
    id: "64",
    name: "青岛棘洪滩水库钓点",
    lat: 36.3135,
    lng: 120.2532,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "山东 青岛 城阳",
    distanceLabel: "全国钓点",
    rating: 4.34,
  },
  {
    id: "65",
    name: "大连碧流河水库钓点",
    lat: 39.7582,
    lng: 122.3918,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、鲢鳙",
    region: "辽宁 大连 普兰店",
    distanceLabel: "全国钓点",
    rating: 4.46,
  },
  {
    id: "66",
    name: "沈阳浑河城市钓点",
    lat: 41.7331,
    lng: 123.4328,
    waterCategory: "江河",
    fish: "鲫鱼、鲤鱼、鲶鱼",
    region: "辽宁 沈阳 浑河",
    distanceLabel: "全国钓点",
    rating: 4.15,
  },
  {
    id: "67",
    name: "银川阅海湖钓点",
    lat: 38.5127,
    lng: 106.2247,
    waterCategory: "湖泊",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "宁夏 银川 阅海湖",
    distanceLabel: "全国钓点",
    rating: 4.28,
  },
  {
    id: "68",
    name: "乌鲁木齐红雁池水库",
    lat: 43.7372,
    lng: 87.6209,
    waterCategory: "水库",
    fish: "鲫鱼、鲤鱼、冷水鱼",
    region: "新疆 乌鲁木齐",
    distanceLabel: "全国钓点",
    rating: 4.24,
  },
  {
    id: "69",
    name: "拉萨河滨河钓点",
    lat: 29.6428,
    lng: 91.1409,
    waterCategory: "江河",
    fish: "高原冷水鱼",
    region: "西藏 拉萨 拉萨河",
    distanceLabel: "全国钓点",
    rating: 4.1,
  },
  {
    id: "70",
    name: "海口南渡江钓点",
    lat: 20.0167,
    lng: 110.3574,
    waterCategory: "江河",
    fish: "罗非、鲶鱼、鲤鱼",
    region: "海南 海口 南渡江",
    distanceLabel: "全国钓点",
    rating: 4.22,
  },
  {
    id: "71",
    name: "三亚宁远河钓点",
    lat: 18.2889,
    lng: 109.4216,
    waterCategory: "江河",
    fish: "罗非、鲈鱼、鲶鱼",
    region: "海南 三亚 宁远河",
    distanceLabel: "全国钓点",
    rating: 4.18,
  },
  {
    id: "72",
    name: "佛山亚洲艺术公园钓场",
    lat: 23.0172,
    lng: 113.1298,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、罗非",
    region: "广东 佛山 黑坑",
    distanceLabel: "全国钓点",
    rating: 4.36,
  },
  {
    id: "73",
    name: "杭州城西休闲钓场",
    lat: 30.2968,
    lng: 120.0255,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "浙江 杭州 黑坑",
    distanceLabel: "全国钓点",
    rating: 4.45,
  },
  {
    id: "74",
    name: "南京江宁竞技钓场",
    lat: 31.8954,
    lng: 118.8349,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "江苏 南京 江宁",
    distanceLabel: "全国钓点",
    rating: 4.42,
  },
  {
    id: "75",
    name: "郑州龙湖休闲钓场",
    lat: 34.7936,
    lng: 113.7448,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、草鱼",
    region: "河南 郑州 郑东新区",
    distanceLabel: "全国钓点",
    rating: 4.3,
  },
  {
    id: "76",
    name: "天津西青竞技钓场",
    lat: 39.0654,
    lng: 117.0085,
    waterCategory: "黑坑",
    fish: "鲫鱼、鲤鱼、青鱼",
    region: "天津 西青 黑坑",
    distanceLabel: "全国钓点",
    rating: 4.32,
  },
];

type SeedCity = {
  province: string;
  city: string;
  lat: number;
  lng: number;
};

const TARGET_SPOT_COUNT = 3000;

const SEED_CITIES: SeedCity[] = [
  { province: "北京", city: "北京", lat: 39.9042, lng: 116.4074 },
  { province: "天津", city: "天津", lat: 39.3434, lng: 117.3616 },
  { province: "上海", city: "上海", lat: 31.2304, lng: 121.4737 },
  { province: "重庆", city: "重庆", lat: 29.563, lng: 106.5516 },
  { province: "河北", city: "石家庄", lat: 38.0428, lng: 114.5149 },
  { province: "河北", city: "承德", lat: 40.9529, lng: 117.9634 },
  { province: "山西", city: "太原", lat: 37.8706, lng: 112.5489 },
  { province: "山西", city: "运城", lat: 35.0267, lng: 111.0075 },
  { province: "内蒙古", city: "呼和浩特", lat: 40.8426, lng: 111.7492 },
  { province: "内蒙古", city: "赤峰", lat: 42.2586, lng: 118.8876 },
  { province: "辽宁", city: "沈阳", lat: 41.8057, lng: 123.4315 },
  { province: "辽宁", city: "大连", lat: 38.914, lng: 121.6147 },
  { province: "吉林", city: "长春", lat: 43.8171, lng: 125.3235 },
  { province: "吉林", city: "松原", lat: 45.1411, lng: 124.8251 },
  { province: "黑龙江", city: "哈尔滨", lat: 45.8038, lng: 126.535 },
  { province: "黑龙江", city: "牡丹江", lat: 44.5517, lng: 129.6332 },
  { province: "江苏", city: "南京", lat: 32.0603, lng: 118.7969 },
  { province: "江苏", city: "苏州", lat: 31.2989, lng: 120.5853 },
  { province: "浙江", city: "杭州", lat: 30.2741, lng: 120.1551 },
  { province: "浙江", city: "宁波", lat: 29.8683, lng: 121.544 },
  { province: "安徽", city: "合肥", lat: 31.8206, lng: 117.2272 },
  { province: "安徽", city: "六安", lat: 31.7337, lng: 116.5232 },
  { province: "福建", city: "福州", lat: 26.0745, lng: 119.2965 },
  { province: "福建", city: "厦门", lat: 24.4798, lng: 118.0894 },
  { province: "江西", city: "南昌", lat: 28.682, lng: 115.8582 },
  { province: "江西", city: "九江", lat: 29.7051, lng: 116.0019 },
  { province: "山东", city: "济南", lat: 36.6512, lng: 117.1201 },
  { province: "山东", city: "青岛", lat: 36.0671, lng: 120.3826 },
  { province: "河南", city: "郑州", lat: 34.7466, lng: 113.6254 },
  { province: "河南", city: "信阳", lat: 32.147, lng: 114.091 },
  { province: "湖北", city: "武汉", lat: 30.5928, lng: 114.3055 },
  { province: "湖北", city: "宜昌", lat: 30.6919, lng: 111.2865 },
  { province: "湖南", city: "长沙", lat: 28.2282, lng: 112.9388 },
  { province: "湖南", city: "岳阳", lat: 29.3571, lng: 113.1287 },
  { province: "广东", city: "广州", lat: 23.1291, lng: 113.2644 },
  { province: "广东", city: "深圳", lat: 22.5431, lng: 114.0579 },
  { province: "广西", city: "南宁", lat: 22.817, lng: 108.3669 },
  { province: "广西", city: "桂林", lat: 25.2736, lng: 110.2902 },
  { province: "海南", city: "海口", lat: 20.0442, lng: 110.1999 },
  { province: "海南", city: "三亚", lat: 18.2528, lng: 109.5119 },
  { province: "四川", city: "成都", lat: 30.5728, lng: 104.0668 },
  { province: "四川", city: "南充", lat: 30.8378, lng: 106.1107 },
  { province: "贵州", city: "贵阳", lat: 26.647, lng: 106.6302 },
  { province: "贵州", city: "兴义", lat: 25.092, lng: 104.8955 },
  { province: "云南", city: "昆明", lat: 25.0389, lng: 102.7183 },
  { province: "云南", city: "大理", lat: 25.6065, lng: 100.2676 },
  { province: "西藏", city: "拉萨", lat: 29.652, lng: 91.1721 },
  { province: "陕西", city: "西安", lat: 34.3416, lng: 108.9398 },
  { province: "甘肃", city: "兰州", lat: 36.0611, lng: 103.8343 },
  { province: "青海", city: "西宁", lat: 36.6171, lng: 101.7782 },
  { province: "宁夏", city: "银川", lat: 38.4872, lng: 106.2309 },
  { province: "新疆", city: "乌鲁木齐", lat: 43.8256, lng: 87.6168 },
];

const CATEGORY_NAMES: Record<WaterSpotCategory, string[]> = {
  水库: ["水库", "库湾", "大坝湾", "深水湾", "上游湾"],
  湖泊: ["湖", "湿地", "浅滩", "湖湾", "亲水湾"],
  江河: ["江段", "河湾", "水道", "支流", "回水湾"],
  黑坑: ["竞技钓场", "休闲钓场", "垂钓园", "渔乐钓场", "综合钓场"],
};

const CATEGORY_FISH: Record<WaterSpotCategory, string[]> = {
  水库: ["鲫鱼、鲤鱼、草鱼", "翘嘴、鳜鱼、鲢鳙", "青鱼、草鱼、鲤鱼"],
  湖泊: ["鲫鱼、鳊鱼、翘嘴", "鲫鱼、鲤鱼、黑鱼", "鲤鱼、草鱼、黄颡鱼"],
  江河: ["鲤鱼、鲶鱼、黄颡鱼", "鳊鱼、翘嘴、鲶鱼", "鲫鱼、鲤鱼、白条"],
  黑坑: ["鲫鱼、鲤鱼、青鱼", "鲫鱼、鲤鱼、草鱼", "罗非、鲫鱼、鲤鱼"],
};

function seededNoise(seed: number) {
  const x = Math.sin(seed * 12.9898) * 43758.5453;
  return x - Math.floor(x);
}

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

function createGeneratedSpot(index: number): FishingSpot {
  const city = SEED_CITIES[index % SEED_CITIES.length];
  const categories = WATER_SPOT_CATEGORIES;
  const waterCategory = categories[index % categories.length];
  const nameParts = CATEGORY_NAMES[waterCategory];
  const fishOptions = CATEGORY_FISH[waterCategory];
  const angle = seededNoise(index + 11) * Math.PI * 2;
  const radius = 0.06 + seededNoise(index + 23) * 0.42;
  const latOffset = Math.sin(angle) * radius;
  const lngOffset = Math.cos(angle) * radius;
  const lat = Number(clamp(city.lat + latOffset, 18.1, 53.5).toFixed(5));
  const lng = Number(clamp(city.lng + lngOffset, 73.5, 134.7).toFixed(5));
  const rating = Number((4 + seededNoise(index + 47) * 0.9).toFixed(2));
  const serial = String(index + 1).padStart(4, "0");
  const suffix = nameParts[index % nameParts.length];

  return {
    id: String(CURATED_FISHING_SPOTS.length + index + 1),
    name: `${city.city}${suffix}${serial}`,
    lat,
    lng,
    waterCategory,
    fish: fishOptions[index % fishOptions.length],
    region: `${city.province} ${city.city}`,
    distanceLabel: "全国钓点",
    rating,
  };
}

const generatedCount = Math.max(0, TARGET_SPOT_COUNT - CURATED_FISHING_SPOTS.length);

export const FALLBACK_FISHING_SPOTS: FishingSpot[] = [
  ...CURATED_FISHING_SPOTS,
  ...Array.from({ length: generatedCount }, (_, index) =>
    createGeneratedSpot(index)
  ),
];

export function getFallbackFishingSpotById(id: string): FishingSpot | undefined {
  return FALLBACK_FISHING_SPOTS.find((s) => s.id === id);
}
